import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/Layout";
import profilePic from "../../public/images/profile/office logoq111111111111111.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { FaArrowUpRightFromSquare } from "react-icons/fa6";
import HireMe from "@/components/HireMe";
import TransitionEffects from "@/components/TransitionEffects";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>williams</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffects/>
      <main className="flex items-center text-dark w-full dark:text-light min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between gap-6 w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="office"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex-col items-center self-center text-left lg:w-full lg:text-center md:text-sm sm:text-xs">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl "
              />
              <p className="my-4 text-base font-medium">
                As a skilled front end developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start lg:self-center">
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="bg-dark flex gap-2 items-center p-2.5 text-light px-5 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark transition-all border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  resume <FaArrowUpRightFromSquare />
                </Link>
                <Link
                  href="/mailto:williamsgoddey11@gmail.com"
                  target={"_blank"}
                  className="ml-4 font-semibold capitalize dark:text-light text-dark underline md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
